### PR TITLE
Implemented MODE Z for FtpClient

### PR DESCRIPTION
**Pull request by Flofler**
I implemented MODE Z for FtpClient to save bandwidth and improve transfer times.

### CODE REVIEW

**Comment by Flofler** [comment]
I'm not sure if this is your preferred way to implement this with a wrapping socket. Alternatively I could change any code that is using the getInputStream() and getOutputStream() of the Socket. But then any new code that is using the Socket must know that you will have to wrap an Inflater- or DeflaterOutputStream around it.

Another solution would be to hide the Socket inside a wrapper class completely.

**Comment by Flofler** [comment]
Hi @garydgregory 

sorry, I didn't know that. This is my first PR. I fixed all issues and ran 'mvn' by myself and it was successful.

**Comment by garydgregory** [comment]
Interesting... it does not look directly related, needs investigating...

**Comment by garydgregory** [comment]
Hello @Flofler 
Would you please rebase on git master? The CodeQL issues should be resolved.

**Comment by Flofler** [comment]
Hi @garydgregory I succesfully rebased on master. You can start the workflows again :)

**Pull request merged**
