### PR TITLE
Fix VMS ftp LIST parsing - allocated part is optional.

### PR DESCRIPTION
**Pull request by bravehorsie**
Signed-off-by: rogrigor <roman.grigoriadi@dhl.com>

### CODE REVIEW

**Comment by bravehorsie** [comment]
This PR fixes a failure to parse server output on LIST command when size / allocated part is missing slash and allocated value. I am not sure if there is any specification on that subject to make clear if this is a valid server output or not, however MultiNet FTP Server Process V5.1(16) does this reply, for example:
```
FILE123.DAT;1
64   4-MAR-2019 00:04 [USR,USRGROUP] (RWED,RWED,RWED,R)
FILE456.DAT;1
102  28-APR-2013 23:12 [USR,USRGROUP] (RWED,RWED,RWED,R)
```

**Comment by bravehorsie** [comment]
If I try to connect to that server with FileZilla client the LIST response is parsed without problems.

**Comment by sebbASF** [comment]
looks ok to me

**Comment by bravehorsie** [comment]
Thank you @sebbASF ! Is there anything I can help with moving this change towards release?

**Pull request merged**
