### PR TITLE
Hostname used in hostname verification

### PR DESCRIPTION
**Pull request by tobias-**
Previously, the ip was used in hostname validation, causing it
to always fail unless the ip was in the certificate making MitM
easy.

By adding the following two lines, the validation of certificate
will be more like a browser.
client.setEndpointCheckingEnabled(true);
client.setTrustManager(TrustManagerUtils.getDefaultTrustManager(null))

The old behaviour of validating by ip is still available by connecting
using the ip (yet again, similar to browser).

The ftp server certificate has had it's CN changed from "ftpserver"
to "localhost" in order to match the hostname being connected to.

### CODE REVIEW

**Comment by tobias-** [comment]
This is for issue https://issues.apache.org/jira/browse/NET-689

**Comment by garydgregory** [comment]
Hi @tobias- 
You issue description mentions:
```
client.setTrustManager(TrustManagerUtils.getDefaultTrustManager(null))
```
but I do not see that in this PR. What am I missing?

**Comment by garydgregory** [comment]
Thank you for your patch but please still reply to my query above.
Committed with:
```
commit 7827f0549526920b91aa2e62d2a1e7682c36e1e7
Author: Gary Gregory <garydgregory@gmail.com> 2020-10-03 09:38:39
Committer: Gary Gregory <garydgregory@gmail.com> 2020-10-03 09:38:39
Parent: bcfb12594d1f9e7c2d784210a1e77bc402d5894f (Bump actions/setup-java from v1.4.2 to v1.4.3 #62.)
Branches: master, origin/master

[NET-689] Hostname is not set on the SSLSocket causing
isEndpointCheckingEnabled to fail.
The main side of this commit is from
https://github.com/apache/commons-net/pull/63 but the test side has been
rewritten to test endpoint checking as both enabled and disabled.
```
Closing.

**Comment by tobias-** [comment]
> Hi @tobias-
> You issue description mentions:
> 
> ```
> client.setTrustManager(TrustManagerUtils.getDefaultTrustManager(null))
> ```
> 
> but I do not see that in this PR. What am I missing?

Since there is no way of creating a valid certificate for localhost. I cannot add that line and get tests to pass.

**Comment by tobias-** [comment]
@garydgregory Uhmm.. I understand that you get shit PR's, but can you allow me more than 10 minutes to answer your question before closing my PR?

**Comment by tobias-** [comment]
@garydgregory Ok, now I understand your comment. You merged the PR in another system. Either way, my answer stands, It's impossible to add that line without a valid certificate, which you cannot distribute. I felt that particular part of the test was a bit outside of my scope, as there were no tests for any of the certificate validating functionality, and the trust manager wasn't involved in that particular part of validating the certificate.

**Pull request closed without merging**
