### PR TITLE
Bulletproof TFTPServerPathTest

### PR DESCRIPTION
**Pull request by jkbkupczyk**
- Rewrite TFTPServerPathTest
- Add the `TFTPServer::getPort` method to return TFTPServer port

This PR tries to get rid of notoriously failing TFTPServerPathTest on Windows 8 on CI pipeline with the message `TFTPServerPathTest.testReadOnly:82 Couldn't clear output location, deleted= ==> expected: <false> but was: <true>`

FYI
@garydgregory @kinow

### CODE REVIEW

**Review by kinow — COMMENTED** [review]
Code looks good, but there might be something else that needs to be done in the new test, CI failing on ubuntu + Java 8

```
Error:  Failures: 
Error:    TFTPServerPathTest.testWriteOnly:154 expected: <false> but was: <true>
```

Thank you!

**Comment by jkbkupczyk** [comment]
> Code looks good, but there might be something else that needs to be done in the new test, CI failing on ubuntu + Java 8
> 
> ```
> Error:  Failures: 
> Error:    TFTPServerPathTest.testWriteOnly:154 expected: <false> but was: <true>
> ```
> 
> Thank you!

Thank you @kinow for the fast response!
I removed the logic of verifying the written contents and moved it to another test `TFTPServerPathTest::testWriteVerifyContents`. I think it should work RN :)

**Comment by garydgregory** [comment]
@jkbkupczyk 
Would you please rebase on master?

**Comment by jkbkupczyk** [comment]
> @jkbkupczyk Would you please rebase on master?

done

**Comment by garydgregory** [comment]
TY @jkbkupczyk !

**Comment by jkbkupczyk** [comment]
Thank you @garydgregory and @kinow for review!

**Comment by garydgregory** [comment]
@jkbkupczyk 
Still fails : https://github.com/apache/commons-net/actions/runs/6213336399/job/16864291327

**Comment by jkbkupczyk** [comment]
> @jkbkupczyk Still fails : https://github.com/apache/commons-net/actions/runs/6213336399/job/16864291327

Hm, I think it's because files have the same name, I will create a patch that will address this issue.

**Comment by garydgregory** [comment]
> > @jkbkupczyk Still fails : https://github.com/apache/commons-net/actions/runs/6213336399/job/16864291327
> 
> Hm, I think it's because files have the same name, I will create a patch that will address this issue.

TY!

**Comment by jkbkupczyk** [comment]
> > > @jkbkupczyk Still fails : https://github.com/apache/commons-net/actions/runs/6213336399/job/16864291327
> > 
> > 
> > Hm, I think it's because files have the same name, I will create a patch that will address this issue.
> 
> TY!

I created patch #184

**Pull request merged**
