### PR TITLE
Add IMAPReply tests and documentation fixes 

### PR DESCRIPTION
**Pull request by jkbkupczyk**
- Updates ImapReply::isContinuation documentation to reflect method contract
- Fixes some Javadoc typos in AuthenticatingIMAPClient::AUTH_METHOD
- Migrates IMAPTest to JUnit5
- Adds IMAPReply tests (all data for tests comes from [RFC-3501)](https://datatracker.ietf.org/doc/html/rfc3501))

I also wonder, can we maybe add _junit-jupiter-params_ artifact to the project, so we can write [parameterized tests](https://junit.org/junit5/docs/current/user-guide/#writing-tests-parameterized-tests)?

FYI: @kinow @garydgregory

### CODE REVIEW

**Review by kinow — APPROVED** [review]
Changes look good to me. The GH Actions failure has a test failure but that's already happening on `master`. Thanks @jkbkupczyk

**Review by jkbkupczyk — COMMENTED** [review]
question here, are those comments (`kate: ident...`) necessary?

**Comment by garydgregory** [comment]
Let's fix master before we do anything else. I'll look today.

It is ok to add the Junit test dependency for parameterized testing.

**Comment by garydgregory** [comment]
@jkbkupczyk 

OK, I finally nailed the bulletproofing on the failing test.

Would you please rebase this PR on master? Then we should see a green build...

TY!

**Review by garydgregory — CHANGES_REQUESTED** [review]
@jkbkupczyk Please rebase on master.

**Comment by garydgregory** [comment]
Ah, no, got another random failure on master for Java 8 on Windows, which is what I am using locally...

**Comment by garydgregory** [comment]
@jkbkupczyk 

OK, now you can rebase.

**Comment by kinow** [comment]
Still seeing the same failure I saw yesterday on `master`. I have a Windows VM at $work, but haven't had much time to set up or test anything on that machine (using that to write docs/sharepoint/etc :disappointed: ). Maybe someone else can reproduce and try to fix the test on Win.

**Comment by garydgregory** [comment]
This PR looks odd, you need to only have your commits in here. Git can be tricky sometimes...

**Comment by jkbkupczyk** [comment]
> This PR looks odd, you need to only have your commits in here. Git can be tricky sometimes...

ahh, I did it through Intellij, should have done it manually...

**Comment by garydgregory** [comment]
😜

**Comment by jkbkupczyk** [comment]
> 😜 time to redo it then

ok 😁 will close that PR and open a new one, maybe I enhance this change add parameterized tests 😀

**Comment by garydgregory** [comment]
You don't need to close this PR and open a new one, this creates noise on the mailing list and disconnects the history of the issue. It's better to keep it here IMO.

**Comment by jkbkupczyk** [comment]
I think it's good RN. Would you mind looking at this @garydgregory, please?

**Comment by garydgregory** [comment]
I kicked off the builds...

**Comment by jkbkupczyk** [comment]
Thank you @garydgregory and @kinow for review 😊

**Pull request merged**
