### PR TITLE
[NET-642] Creating a unit-test that proves that execPROT resets the p…

### PR DESCRIPTION
**Pull request by DJGummikuh**
…roxy settings on FTPS Clients.

### CODE REVIEW

**Comment by garydgregory** [comment]
Thank you for the unit test. We are all volunteers in this project. If you want a speedier resolution, please provide a patch for a fix. Thank you!

**Comment by DJGummikuh** [comment]
Hey! 

I honestly would provide a patch for that issue if I could. However I honestly do not understand a whole lot of what you're doing there with all those socket factories so even if I were able to satisfy my own unit tests, I would not have enough confidence in my work that I would feel it to be a good idea to merge it in :-|

**Comment by garydgregory** [comment]
It's up to you to pick the challenge for yourself or wait... ;-)

**Comment by DJGummikuh** [comment]
uhm, what does that closed now mean? Has the issue been resolved?

**Comment by markt-asf** [comment]
The PR was against trunk
The trunk branch was deleted as all Commons projects use maser in preference to trunk. That automatically closed all PRs against trunk. 
I'll re-open this but you'll need to modify the PR to be against master rather than trunk.

**Comment by DJGummikuh** [comment]
done! Thanks!

**Review by garydgregory — CHANGES_REQUESTED** [review]
@DJGummikuh 
Please see `FTPSClientTest` for an example of a standalone FTPS test. May I suggest that you provide a similar test instead of one that relies on an external FTPS server? Make sure you rebase on master first.

**Comment by DJGummikuh** [comment]
Nevermind

**Comment by Ynhockey** [comment]
Hi, we were having the same issue with version 3.6, if the issue was closed does it mean it was resolved in 3.8? Thanks!

**Comment by garydgregory** [comment]
Hello @Ynhockey ,
You will have to test the latest release to check your use case. Since @DJGummikuh closed the issue, maybe they can answer if their use case works.

**Comment by DJGummikuh** [comment]
@Ynhockey my Test showed the ill-behavior. You can run it against current master, to figure out if the issue still persists.
However, since my tests were not up to standard and I honestly did not have the juice in me to analyze the test template for commons-net in order to be able to rewrite the test I just basically gave up on that issue. In our Software, we opted to simply forbid users to use FTPS with Proxies, and the handful of complaining customers we successfully lobbied to move over to SFTP, which circumvents this issue altogether :shrug:

**Pull request closed without merging**
