### PR TITLE
Use `assertThrows` in test

### PR DESCRIPTION
**Pull request by basil**

### CODE REVIEW

**Comment by garydgregory** [comment]
Hello @basil 

Thank you for ylthe PR.

Is that the only place in the code base that needs this change?

**Comment by basil** [comment]
Hi @garydgregory, many thanks for your incredible maintenance of this component. I don't know if this is the only place in this code base that needs this change, but (for now) it is what I am willing to contribute to this project. Thanks again, Basil.

**Comment by garydgregory** [comment]
@basil I've rerun this build many times and it fails, which should be unrelated to your change. Still, please rebase your PR in case that helps. TY!

**Comment by basil** [comment]
Done

I tested this locally with `mvn clean verify -Dtest=org.apache.commons.net.SubnetUtilsTest`

**Pull request merged**
