### PR TITLE
Change Class "org.apache.commons.net.ftp.parser.MVSFTPEntryParser" to support more datasets

### PR DESCRIPTION
**Pull request by haegar9766**
Current MVSFTPEntryParser code doesn't support all possible datasets because some RECFM options (e.g. "FBA") are not listet in "static final String FILE_LIST_REGEX" (see also Jira-Ticket [NET-725](https://issues.apache.org/jira/browse/NET-725)). This PR should fix this problem. 

- RECFM (record format) of an MVS dataset is not a relevant information about a dataset. Therefore it should be ignored in definition of "static final String FILE_LIST_REGEX".
- Method "parseFileList(final String entry)" should also migrated and archived datasets.

### CODE REVIEW

**Comment by garydgregory** [comment]
@haegar9766 
Thank you for your PR. Please add unit tests.

**Comment by haegar9766** [comment]
@garydgregory 
How could i provide a unit test for this? To test the code, the appropriate environment is needed. In this case an MVS system with FTP server and user datasets. For a unit test datasets with e.g. RECFM=FBA and migrated datasets have to be available.

**Comment by haegar9766** [comment]
@garydgregory 
Sorry for the misunderstanding. I now also updated the existing test class "MVSFTPEntryParserTest".

**Comment by garydgregory** [comment]
@haegar9766 
Thank you for your update. 
Run `mvn` locally before your push to catch these build failures.

**Comment by haegar9766** [comment]
@garydgregory 
After fixing code style errors "mvn" could now build my branch without any errors.

**Pull request merged**
