### PR TITLE
NET-642 Fix review requested changes

### PR DESCRIPTION
**Pull request by gremi64**
I can't modify [YaniM](https://github.com/YaniM) #90 PR, so i created mine from his branch.

I tried to update directly from his PR, but i'm not allowed to do so, and since he has not commit anything in the past year... i'm not sure he his active anymore :/

### CODE REVIEW

**Comment by garydgregory** [comment]
@gremi64 
PR #90 has been merged. Please verify and close this PR if your use case works.

**Comment by garydgregory** [comment]
@gremi64 ping?

**Comment by gremi64** [comment]
Thanks @garydgregory !
I'll give it a try this week !
But my PR can already be closed.

**Comment by gremi64** [comment]
@garydgregory it works like a charm with the new 3.9.0-SNAPSHOT (master) !

Can't wait for the release in mvn repo :heart:

**Pull request closed without merging**
